/**
 * Created by kee on 15/10/09.
 */
export const POST_INFO_LOAD = 'POST_INFO_LOAD';
export const POST_INFO_LOAD_SUCCESS = 'POST_INFO_LOAD_SUCCESS';
export const POST_INFO_LOAD_FAIL = 'POST_INFO_LOAD_FAIL';
export const POST_COMMENT_CREATE_LOAD = 'POST_COMMENT_CREATE_LOAD';
export const POST_COMMENT_CREATE_SUCCESS = 'POST_COMMENT_CREATE_SUCCESS';
export const POST_COMMENT_CREATE_FAIL = 'POST_COMMENT_CREATE_FAIL';
